name: Deploy to heroku with devopsdocker

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: deploy to heroku
      uses: akhileshns/heroku-deploy@v3.12.12 
      with:
        heroku_api_key: {{secrets.HEROKU_API_KEY}}
        heroku_app_name: "devopsdocker-tomnguyen"
        heroku_email: "thongola@hotmail.com"
